<?php /** @var \Bravo\Dto\Article $article */ ?>
<?php foreach(array_chunk($this->articles, 2) as $articles): ?>
<div class="row">
    <?php foreach($articles as $article): ?>
    <div class="col-sm-6">
        <div class="panel panel-default article-card">
            <div class="panel-heading">
                <?=$article->getPubDate()->format("D, d M Y H:i:s")?>
                <span class="pull-right">
                    <div class="fb-like"
                         data-href="<?= $article->getLink() ?>"
                         data-layout="button_count"
                         data-action="like"
                         data-size="small"
                         data-show-faces="false"
                         data-share="true"
                    >
                    </div>
                </span>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-12">
                        <h3>
                            <a href="<?= $article->getLink() ?>">
                                <?=$article->getTitle()?>
                            </a>
                        </h3>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="<?= $article->getLink() ?>">
                            <img src="<?= $article->getImage() ?>" alt="<?=$article->getTitle()?>" class="img-responsive">
                        </a>
                    </div>
                    <div class="col-sm-6">
                        <p>
                            <?=$article->getDescription()?>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php endforeach; ?>
</div>
<?php endforeach; ?>
