<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading"></div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="first-name" class="col-sm-2 control-label">First name</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="first-name" name="first-name" type="text" placeholder="ex. Ninoslav">
                    </div>
                </div>
                <div class="form-group">
                    <label for="last-name" class="col-sm-2 control-label">Last name</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="last-name" name="last-name" type="text" placeholder="ex. Jaric">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>