<html lang="en">
<head>
    <title><?=isset($this->title) ? $this->title : "Yahoo-portal"?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="/css/fonts.css">
    <link rel="stylesheet" href="/css/style.css">
    <script src="/js/script.js"></script>
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 navbar-parent">
            <div class="navbar-y">
                <div class="container">
                    <div class="row">
                        <div class="col-md-2">
                            <h1>Y-news</h1>
                        </div>
                        <div class="col-md-8">
                            <div class="btn-group btn-group-justified menu menu-margin-top" role="group" aria-label="...">
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/">Home</a></div>
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/news/science">Science</a></div>
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/news/tech">Tech</a></div>
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/news/world">World</a></div>
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/news/politics">Politics</a></div>
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/news/health">Health</a></div>
                                <div class="btn-group" role="group"><a class="btn btn-default" href="/contact">Contact</a></div>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <form action="#">
                                <div class="form-group search menu-margin-top">
                                    <input type="text" class="form-control" id="query" placeholder="Search">
                                    <button>
                                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container top-margin">
    <div class="row">
        <div class="col-sm-12">
            <h1 class="text-center">
                <?=isset($this->title) ? $this->title : "Yahoo news"?>
            </h1>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <hr/>
        </div>
    </div>
    <div class="main-content">
        <?=$this->getContent()?>
    </div>
</div>
<footer>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="collapse navbar-collapse" id="footer">
                    <p>
                        Copyleft &copy; 2016 <strong>Y-news</strong>. All lefts Reserved
                    </p>
                    <ul class="nav navbar-nav pull-right">
                        <li class="active"><a href="/">Home</a></li>
                        <li><a href="/about">About us</a></li>
                        <li><a href="/contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

</body>
</html>